spring.application.name=backend

# Konfigurasi Koneksi Database PostgreSQL ke aaPanel
spring.datasource.url=jdbc:postgresql://192.168.63.128:5432/pinterq_db
spring.datasource.username=pinterq_db
spring.datasource.password=FCYKExTR4Epbzz8w
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfigurasi Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Pengaturan Server Lokal
server.port=8081

# Gemini API Configuration
gemini.api.key=AIzaSyAWeNkP73ABW_24fOIorR95PyYLKztMC_c
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# JWT Configuration
jwt.secret=PinterQ-Secret-Key-2026-Secure-Random-256bit-Token
jwt.expiration-ms=86400000
